"""A sandboxed shell a hunting agent can actually call.

    Reading source code isn't enough to understand how it behaves under stress ... they
    compile fragments, build small versions, and attack them. The biggest jump in quality
    came from giving Hunters a sandbox to crash binaries.
        -- Cloudflare, "Build your own vulnerability harness"

Until now the sandbox only ran a proof of concept after a finding was already filed, which
is the wrong end of the process: by then the hunter has committed to a theory it could not
test. This gives the hunter the sandbox during the hunt, so "does this parser actually
overflow" is a question it answers by running the parser rather than by reasoning about it.

The shim is a generated shell script rather than a tool call, because the agent already has
a Bash tool and a tightly scoped `Bash(<path>:*)` permission is far easier to reason about
than a new protocol. The agent can run anything it likes *through* the shim, and nothing at
all outside it: the target is mounted read only, the network is off, and every limit from
SandboxConfig is applied to the container rather than trusted to the command.
"""

from __future__ import annotations

import os
import shlex
import stat
from pathlib import Path

from vulness.config import SandboxConfig

# Marks the harness's own importability check so it is not counted as hunter usage: a
# metric that includes its own probe reports the capability as used when nobody used it.
PROBE_MARKER = "vulness:probe"

# Experiments are probes, not builds. A hunter that needs longer than this is compiling a
# project, which belongs on the wishlist as a build environment request.
SHIM_TIMEOUT_S = 90

_TEMPLATE = """#!/bin/sh
# Generated by vulness. Runs one command inside a locked down container.
# Runs as the calling user, not root. With --cap-drop=ALL the container loses
# CAP_DAC_OVERRIDE, so root cannot read a host directory owned by someone else and
# /target comes back "Permission denied". Matching the host uid is what makes it readable.
#   target  -> /target  (read only)
#   scratch -> /scratch (writable, your working directory)
# No network. No capabilities. Limits are enforced by the container, not by this script.
set -eu

if [ "$#" -eq 0 ]; then
  echo "usage: $(basename "$0") <command> [args...]" >&2
  exit 2
fi

# Record every invocation. Without this there is no way to tell whether hunters actually
# use the sandbox, and "we gave them a sandbox" is an assumption rather than a measurement.
printf '%s\t%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >> {logfile} 2>/dev/null || true

exec timeout {timeout}s docker run --rm \\
  --user {uid}:{gid} \\
  --network=none \\
  --read-only \\
  --cap-drop=ALL \\
  --security-opt=no-new-privileges \\
  --pids-limit={pids} \\
  --memory={memory} \\
  --cpus={cpus} \\
  --tmpfs /tmp:rw,size={tmpfs} \\
  -v {target}:/target:ro \\
  -v {scratch}:/scratch:rw \\
  -w /scratch \\
  --label vulness.shim=1 \\
  {image} \\
  sh -c "$*"
"""


def write_shim(
    path: Path, *, target: Path, scratch: Path, cfg: SandboxConfig, timeout_s: int = SHIM_TIMEOUT_S
) -> Path:
    """Emit an executable shim bound to one target and one scratch directory.

    Paths are quoted at generation time and the container flags are fixed here, so nothing
    the agent passes as an argument can reach the docker invocation itself: its input only
    ever becomes the argument of the inner `sh -c`, inside the sandbox.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    scratch.mkdir(parents=True, exist_ok=True)
    path.write_text(
        _TEMPLATE.format(
            timeout=int(timeout_s),
            uid=os.getuid(),
            gid=os.getgid(),
            pids=int(cfg.pids_limit),
            memory=shlex.quote(cfg.memory),
            cpus=cfg.cpus,
            tmpfs=shlex.quote(cfg.tmpfs_size),
            logfile=shlex.quote(str((scratch.parent / "invocations.log").resolve())),
            target=shlex.quote(str(target.resolve())),
            scratch=shlex.quote(str(scratch.resolve())),
            image=shlex.quote(cfg.image),
        )
    )
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
    return path


def probe_imports(shim: Path, module_hint: str | None = None) -> tuple[bool, str]:
    """Can anything in the target actually be exercised in this image?

    Answering this once per repo is what turns "the hunters ignored the sandbox" into a
    fact the harness can act on. A hunter that silently concludes the sandbox is useless
    reports nothing and looks identical to a hunter that found nothing.
    """
    import subprocess

    probe = (
        "python3 -c \"import sys;sys.path.insert(0,'/target');"
        f"import {module_hint}\" # {PROBE_MARKER}" if module_hint
        else "python3 -c \"import sys;sys.path.insert(0,'/target');print('ok')\""
    ) + f" # {PROBE_MARKER}"
    try:
        r = subprocess.run(
            [str(shim), probe], capture_output=True, text=True, timeout=SHIM_TIMEOUT_S + 15
        )
    except (OSError, subprocess.SubprocessError) as e:
        return False, f"{type(e).__name__}: {e}"[:200]
    if r.returncode == 0:
        return True, "target is importable in this image"
    tail = (r.stderr or r.stdout).strip().splitlines()
    return False, tail[-1][:200] if tail else f"exit {r.returncode}"


def invocation_count(shim: Path) -> int:
    """How many times a hunter reached for the sandbox. Zero is worth knowing."""
    log = shim.parent / "invocations.log"
    if not log.is_file():
        return 0
    try:
        return sum(
            1
            for line in log.read_text().splitlines()
            if line.strip() and PROBE_MARKER not in line
        )
    except OSError:
        return 0


def shim_instructions(shim: Path) -> str:
    """The block appended to a hunter prompt describing what it may now do."""
    return f"""## You can run code

You have a sandbox. Use it: reading a parser tells you what it is supposed to do, running
it tells you what it does.

```
{shim} '<shell command>'
```

- The target is at `/target`, read only. You cannot modify it, and attempting to is itself
  a finding about nothing.
- `/scratch` is your writable working directory. Put test harnesses and fixtures there.
- There is no network. Nothing installs. Use only what the image and the target already have.
- Each call is capped at {SHIM_TIMEOUT_S} seconds.

Worth running rather than reasoning about: feed a crafted input to a parser and read the
actual output, check whether a path join really escapes its root, confirm a comparison is
constant time, see what an error handler prints. If a check needs a toolchain you do not
have, do not fake the result: put it on the `wishlist` and say what would unblock it.
"""
